"""
Ultimate Soccer 3D - Teams & Player Data
Complete team rosters with player attributes, kits, and metadata.
"""
from config import Position, PlayerAttribute

# =============================================================================
# TEAM DEFINITIONS
# =============================================================================

TEAMS = {
    'real_madrid': {
        'name': 'Real Madrid CF',
        'short_name': 'RMA',
        'country': 'Spain',
        'league': 'La Liga',
        'rating': 89,
        'home_color': (1.0, 1.0, 1.0),
        'away_color': (0.1, 0.1, 0.3),
        'third_color': (0.9, 0.5, 0.1),
        'gk_color': (0.2, 0.8, 0.2),
        'formation': '4-3-3',
        'tactic': 'balanced',
        'mentality': 'attacking',
        'players': [
            {'name': 'Courtois', 'number': 1, 'position': Position.GK, 'rating': 89,
             'attrs': {PlayerAttribute.GK_DIVING: 88, PlayerAttribute.GK_HANDLING: 85,
                       PlayerAttribute.GK_KICKING: 75, PlayerAttribute.GK_REFLEXES: 90,
                       PlayerAttribute.GK_POSITIONING: 87, PlayerAttribute.GK_SPEED: 50,
                       PlayerAttribute.PACE: 45, PlayerAttribute.PHYSICAL: 78}},
            {'name': 'Carvajal', 'number': 2, 'position': Position.RB, 'rating': 86,
             'attrs': {PlayerAttribute.PACE: 78, PlayerAttribute.DEFENDING: 82,
                       PlayerAttribute.PHYSICAL: 76, PlayerAttribute.PASSING: 80,
                       PlayerAttribute.DRIBBLING: 78, PlayerAttribute.SHOOTING: 62,
                       PlayerAttribute.STAMINA: 85, PlayerAttribute.CROSSING: 83}},
            {'name': 'Militao', 'number': 3, 'position': Position.CB, 'rating': 84,
             'attrs': {PlayerAttribute.PACE: 80, PlayerAttribute.DEFENDING: 84,
                       PlayerAttribute.PHYSICAL: 83, PlayerAttribute.PASSING: 65,
                       PlayerAttribute.DRIBBLING: 68, PlayerAttribute.SHOOTING: 52,
                       PlayerAttribute.HEADING: 82, PlayerAttribute.STANDING_TACKLE: 83}},
            {'name': 'Alaba', 'number': 4, 'position': Position.CB, 'rating': 84,
             'attrs': {PlayerAttribute.PACE: 74, PlayerAttribute.DEFENDING: 82,
                       PlayerAttribute.PHYSICAL: 78, PlayerAttribute.PASSING: 80,
                       PlayerAttribute.DRIBBLING: 76, PlayerAttribute.SHOOTING: 68,
                       PlayerAttribute.HEADING: 75, PlayerAttribute.LONG_PASSING: 82}},
            {'name': 'Mendy', 'number': 23, 'position': Position.LB, 'rating': 83,
             'attrs': {PlayerAttribute.PACE: 86, PlayerAttribute.DEFENDING: 83,
                       PlayerAttribute.PHYSICAL: 80, PlayerAttribute.PASSING: 68,
                       PlayerAttribute.DRIBBLING: 72, PlayerAttribute.SHOOTING: 48,
                       PlayerAttribute.STAMINA: 88, PlayerAttribute.STANDING_TACKLE: 84}},
            {'name': 'Kroos', 'number': 8, 'position': Position.CM, 'rating': 88,
             'attrs': {PlayerAttribute.PACE: 52, PlayerAttribute.DEFENDING: 65,
                       PlayerAttribute.PHYSICAL: 72, PlayerAttribute.PASSING: 92,
                       PlayerAttribute.DRIBBLING: 80, PlayerAttribute.SHOOTING: 78,
                       PlayerAttribute.VISION: 93, PlayerAttribute.LONG_PASSING: 94,
                       PlayerAttribute.SHORT_PASSING: 92, PlayerAttribute.FREE_KICK: 85}},
            {'name': 'Modric', 'number': 10, 'position': Position.CM, 'rating': 87,
             'attrs': {PlayerAttribute.PACE: 68, PlayerAttribute.DEFENDING: 62,
                       PlayerAttribute.PHYSICAL: 65, PlayerAttribute.PASSING: 90,
                       PlayerAttribute.DRIBBLING: 88, PlayerAttribute.SHOOTING: 76,
                       PlayerAttribute.VISION: 90, PlayerAttribute.BALL_CONTROL: 90,
                       PlayerAttribute.AGILITY: 85, PlayerAttribute.COMPOSURE: 88}},
            {'name': 'Valverde', 'number': 15, 'position': Position.CDM, 'rating': 86,
             'attrs': {PlayerAttribute.PACE: 86, PlayerAttribute.DEFENDING: 76,
                       PlayerAttribute.PHYSICAL: 82, PlayerAttribute.PASSING: 78,
                       PlayerAttribute.DRIBBLING: 78, PlayerAttribute.SHOOTING: 78,
                       PlayerAttribute.STAMINA: 92, PlayerAttribute.INTERCEPTIONS: 80}},
            {'name': 'Vinicius Jr', 'number': 7, 'position': Position.LW, 'rating': 89,
             'attrs': {PlayerAttribute.PACE: 95, PlayerAttribute.DEFENDING: 30,
                       PlayerAttribute.PHYSICAL: 68, PlayerAttribute.PASSING: 72,
                       PlayerAttribute.DRIBBLING: 92, PlayerAttribute.SHOOTING: 80,
                       PlayerAttribute.ACCELERATION: 96, PlayerAttribute.AGILITY: 93,
                       PlayerAttribute.BALL_CONTROL: 90, PlayerAttribute.SPRINT_SPEED: 95}},
            {'name': 'Bellingham', 'number': 5, 'position': Position.ST, 'rating': 88,
             'attrs': {PlayerAttribute.PACE: 78, PlayerAttribute.DEFENDING: 62,
                       PlayerAttribute.PHYSICAL: 80, PlayerAttribute.PASSING: 80,
                       PlayerAttribute.DRIBBLING: 84, PlayerAttribute.SHOOTING: 85,
                       PlayerAttribute.FINISHING: 84, PlayerAttribute.HEADING: 78,
                       PlayerAttribute.COMPOSURE: 85, PlayerAttribute.POSITIONING: 86}},
            {'name': 'Rodrygo', 'number': 11, 'position': Position.RW, 'rating': 84,
             'attrs': {PlayerAttribute.PACE: 90, PlayerAttribute.DEFENDING: 35,
                       PlayerAttribute.PHYSICAL: 62, PlayerAttribute.PASSING: 75,
                       PlayerAttribute.DRIBBLING: 85, PlayerAttribute.SHOOTING: 78,
                       PlayerAttribute.FINISHING: 80, PlayerAttribute.AGILITY: 88}},
        ],
        'subs': [
            {'name': 'Lunin', 'number': 13, 'position': Position.GK, 'rating': 78,
             'attrs': {PlayerAttribute.GK_DIVING: 80, PlayerAttribute.GK_HANDLING: 76,
                       PlayerAttribute.GK_REFLEXES: 82, PlayerAttribute.GK_POSITIONING: 75}},
            {'name': 'Nacho', 'number': 6, 'position': Position.CB, 'rating': 80,
             'attrs': {PlayerAttribute.PACE: 70, PlayerAttribute.DEFENDING: 81,
                       PlayerAttribute.PHYSICAL: 75, PlayerAttribute.PASSING: 68}},
            {'name': 'Camavinga', 'number': 12, 'position': Position.CM, 'rating': 83,
             'attrs': {PlayerAttribute.PACE: 82, PlayerAttribute.DEFENDING: 72,
                       PlayerAttribute.PHYSICAL: 78, PlayerAttribute.PASSING: 78,
                       PlayerAttribute.DRIBBLING: 80, PlayerAttribute.STAMINA: 88}},
            {'name': 'Joselu', 'number': 14, 'position': Position.ST, 'rating': 80,
             'attrs': {PlayerAttribute.PACE: 62, PlayerAttribute.HEADING: 85,
                       PlayerAttribute.PHYSICAL: 82, PlayerAttribute.FINISHING: 80,
                       PlayerAttribute.SHOOTING: 76, PlayerAttribute.POSITIONING: 84}},
            {'name': 'Brahim', 'number': 21, 'position': Position.RW, 'rating': 79,
             'attrs': {PlayerAttribute.PACE: 84, PlayerAttribute.DRIBBLING: 83,
                       PlayerAttribute.PHYSICAL: 58, PlayerAttribute.PASSING: 72,
                       PlayerAttribute.SHOOTING: 72, PlayerAttribute.AGILITY: 88}},
        ],
    },

    'barcelona': {
        'name': 'FC Barcelona',
        'short_name': 'BAR',
        'country': 'Spain',
        'league': 'La Liga',
        'rating': 88,
        'home_color': (0.6, 0.0, 0.15),
        'away_color': (0.0, 0.0, 0.0),
        'third_color': (0.9, 0.75, 0.1),
        'gk_color': (0.2, 0.9, 0.5),
        'formation': '4-3-3',
        'tactic': 'tiki_taka',
        'mentality': 'attacking',
        'players': [
            {'name': 'ter Stegen', 'number': 1, 'position': Position.GK, 'rating': 88,
             'attrs': {PlayerAttribute.GK_DIVING: 87, PlayerAttribute.GK_HANDLING: 85,
                       PlayerAttribute.GK_KICKING: 88, PlayerAttribute.GK_REFLEXES: 89,
                       PlayerAttribute.GK_POSITIONING: 86, PlayerAttribute.GK_SPEED: 48}},
            {'name': 'Cancelo', 'number': 2, 'position': Position.RB, 'rating': 85,
             'attrs': {PlayerAttribute.PACE: 82, PlayerAttribute.DEFENDING: 72,
                       PlayerAttribute.PHYSICAL: 72, PlayerAttribute.PASSING: 85,
                       PlayerAttribute.DRIBBLING: 84, PlayerAttribute.CROSSING: 88}},
            {'name': 'Araujo', 'number': 4, 'position': Position.CB, 'rating': 85,
             'attrs': {PlayerAttribute.PACE: 85, PlayerAttribute.DEFENDING: 86,
                       PlayerAttribute.PHYSICAL: 86, PlayerAttribute.PASSING: 58,
                       PlayerAttribute.HEADING: 82, PlayerAttribute.STANDING_TACKLE: 85}},
            {'name': 'Kounde', 'number': 23, 'position': Position.CB, 'rating': 84,
             'attrs': {PlayerAttribute.PACE: 82, PlayerAttribute.DEFENDING: 83,
                       PlayerAttribute.PHYSICAL: 76, PlayerAttribute.PASSING: 72,
                       PlayerAttribute.DRIBBLING: 75, PlayerAttribute.HEADING: 78}},
            {'name': 'Balde', 'number': 3, 'position': Position.LB, 'rating': 80,
             'attrs': {PlayerAttribute.PACE: 92, PlayerAttribute.DEFENDING: 72,
                       PlayerAttribute.PHYSICAL: 72, PlayerAttribute.PASSING: 72,
                       PlayerAttribute.DRIBBLING: 78, PlayerAttribute.STAMINA: 88}},
            {'name': 'Pedri', 'number': 8, 'position': Position.CM, 'rating': 87,
             'attrs': {PlayerAttribute.PACE: 70, PlayerAttribute.DEFENDING: 62,
                       PlayerAttribute.PHYSICAL: 62, PlayerAttribute.PASSING: 88,
                       PlayerAttribute.DRIBBLING: 90, PlayerAttribute.SHOOTING: 68,
                       PlayerAttribute.VISION: 88, PlayerAttribute.BALL_CONTROL: 91,
                       PlayerAttribute.COMPOSURE: 86, PlayerAttribute.AGILITY: 90}},
            {'name': 'de Jong', 'number': 21, 'position': Position.CDM, 'rating': 85,
             'attrs': {PlayerAttribute.PACE: 78, PlayerAttribute.DEFENDING: 76,
                       PlayerAttribute.PHYSICAL: 78, PlayerAttribute.PASSING: 86,
                       PlayerAttribute.DRIBBLING: 85, PlayerAttribute.SHOOTING: 68,
                       PlayerAttribute.INTERCEPTIONS: 78, PlayerAttribute.BALL_CONTROL: 88}},
            {'name': 'Gavi', 'number': 6, 'position': Position.CM, 'rating': 83,
             'attrs': {PlayerAttribute.PACE: 78, PlayerAttribute.DEFENDING: 68,
                       PlayerAttribute.PHYSICAL: 72, PlayerAttribute.PASSING: 80,
                       PlayerAttribute.DRIBBLING: 82, PlayerAttribute.SHOOTING: 65,
                       PlayerAttribute.AGGRESSION: 85, PlayerAttribute.STAMINA: 90}},
            {'name': 'Raphinha', 'number': 11, 'position': Position.RW, 'rating': 83,
             'attrs': {PlayerAttribute.PACE: 88, PlayerAttribute.DEFENDING: 38,
                       PlayerAttribute.PHYSICAL: 68, PlayerAttribute.PASSING: 75,
                       PlayerAttribute.DRIBBLING: 84, PlayerAttribute.SHOOTING: 78,
                       PlayerAttribute.CROSSING: 82, PlayerAttribute.FREE_KICK: 78}},
            {'name': 'Lewandowski', 'number': 9, 'position': Position.ST, 'rating': 88,
             'attrs': {PlayerAttribute.PACE: 68, PlayerAttribute.DEFENDING: 42,
                       PlayerAttribute.PHYSICAL: 80, PlayerAttribute.PASSING: 72,
                       PlayerAttribute.DRIBBLING: 82, PlayerAttribute.SHOOTING: 92,
                       PlayerAttribute.FINISHING: 95, PlayerAttribute.POSITIONING: 94,
                       PlayerAttribute.HEADING: 88, PlayerAttribute.COMPOSURE: 92}},
            {'name': 'Yamal', 'number': 19, 'position': Position.LW, 'rating': 82,
             'attrs': {PlayerAttribute.PACE: 93, PlayerAttribute.DEFENDING: 28,
                       PlayerAttribute.PHYSICAL: 52, PlayerAttribute.PASSING: 76,
                       PlayerAttribute.DRIBBLING: 88, PlayerAttribute.SHOOTING: 72,
                       PlayerAttribute.ACCELERATION: 94, PlayerAttribute.AGILITY: 92}},
        ],
        'subs': [
            {'name': 'Pena', 'number': 13, 'position': Position.GK, 'rating': 76,
             'attrs': {PlayerAttribute.GK_DIVING: 75, PlayerAttribute.GK_HANDLING: 74,
                       PlayerAttribute.GK_REFLEXES: 78, PlayerAttribute.GK_POSITIONING: 74}},
            {'name': 'Christensen', 'number': 15, 'position': Position.CB, 'rating': 80,
             'attrs': {PlayerAttribute.PACE: 65, PlayerAttribute.DEFENDING: 80,
                       PlayerAttribute.PHYSICAL: 76, PlayerAttribute.PASSING: 72}},
            {'name': 'Felix', 'number': 14, 'position': Position.CF, 'rating': 81,
             'attrs': {PlayerAttribute.PACE: 82, PlayerAttribute.DRIBBLING: 82,
                       PlayerAttribute.PHYSICAL: 62, PlayerAttribute.PASSING: 74,
                       PlayerAttribute.SHOOTING: 78, PlayerAttribute.AGILITY: 85}},
            {'name': 'Ferran', 'number': 7, 'position': Position.LW, 'rating': 79,
             'attrs': {PlayerAttribute.PACE: 85, PlayerAttribute.DRIBBLING: 78,
                       PlayerAttribute.PHYSICAL: 60, PlayerAttribute.PASSING: 72,
                       PlayerAttribute.SHOOTING: 72, PlayerAttribute.POSITIONING: 82}},
        ],
    },

    'manchester_city': {
        'name': 'Manchester City',
        'short_name': 'MCI',
        'country': 'England',
        'league': 'Premier League',
        'rating': 90,
        'home_color': (0.4, 0.75, 0.92),
        'away_color': (0.55, 0.0, 0.25),
        'third_color': (0.0, 0.2, 0.35),
        'gk_color': (0.9, 0.7, 0.1),
        'formation': '4-3-3',
        'tactic': 'tiki_taka',
        'mentality': 'attacking',
        'players': [
            {'name': 'Ederson', 'number': 31, 'position': Position.GK, 'rating': 88,
             'attrs': {PlayerAttribute.GK_DIVING: 86, PlayerAttribute.GK_HANDLING: 82,
                       PlayerAttribute.GK_KICKING: 92, PlayerAttribute.GK_REFLEXES: 87,
                       PlayerAttribute.GK_POSITIONING: 85, PlayerAttribute.GK_SPEED: 60}},
            {'name': 'Walker', 'number': 2, 'position': Position.RB, 'rating': 84,
             'attrs': {PlayerAttribute.PACE: 90, PlayerAttribute.DEFENDING: 80,
                       PlayerAttribute.PHYSICAL: 82, PlayerAttribute.PASSING: 68,
                       PlayerAttribute.DRIBBLING: 72, PlayerAttribute.STAMINA: 86}},
            {'name': 'Dias', 'number': 3, 'position': Position.CB, 'rating': 87,
             'attrs': {PlayerAttribute.PACE: 68, PlayerAttribute.DEFENDING: 88,
                       PlayerAttribute.PHYSICAL: 82, PlayerAttribute.PASSING: 72,
                       PlayerAttribute.HEADING: 84, PlayerAttribute.COMPOSURE: 86}},
            {'name': 'Stones', 'number': 5, 'position': Position.CB, 'rating': 84,
             'attrs': {PlayerAttribute.PACE: 62, PlayerAttribute.DEFENDING: 82,
                       PlayerAttribute.PHYSICAL: 78, PlayerAttribute.PASSING: 80,
                       PlayerAttribute.DRIBBLING: 76, PlayerAttribute.BALL_CONTROL: 80}},
            {'name': 'Gvardiol', 'number': 24, 'position': Position.LB, 'rating': 83,
             'attrs': {PlayerAttribute.PACE: 78, PlayerAttribute.DEFENDING: 82,
                       PlayerAttribute.PHYSICAL: 82, PlayerAttribute.PASSING: 72,
                       PlayerAttribute.DRIBBLING: 74, PlayerAttribute.HEADING: 78}},
            {'name': 'Rodri', 'number': 16, 'position': Position.CDM, 'rating': 90,
             'attrs': {PlayerAttribute.PACE: 62, PlayerAttribute.DEFENDING: 82,
                       PlayerAttribute.PHYSICAL: 85, PlayerAttribute.PASSING: 88,
                       PlayerAttribute.DRIBBLING: 82, PlayerAttribute.SHOOTING: 78,
                       PlayerAttribute.VISION: 86, PlayerAttribute.INTERCEPTIONS: 88,
                       PlayerAttribute.COMPOSURE: 90, PlayerAttribute.LONG_PASSING: 86}},
            {'name': 'De Bruyne', 'number': 17, 'position': Position.CM, 'rating': 91,
             'attrs': {PlayerAttribute.PACE: 72, PlayerAttribute.DEFENDING: 55,
                       PlayerAttribute.PHYSICAL: 76, PlayerAttribute.PASSING: 94,
                       PlayerAttribute.DRIBBLING: 86, PlayerAttribute.SHOOTING: 88,
                       PlayerAttribute.VISION: 95, PlayerAttribute.CROSSING: 92,
                       PlayerAttribute.FREE_KICK: 88, PlayerAttribute.LONG_PASSING: 94,
                       PlayerAttribute.COMPOSURE: 90, PlayerAttribute.CURVE: 88}},
            {'name': 'Bernardo', 'number': 20, 'position': Position.CM, 'rating': 87,
             'attrs': {PlayerAttribute.PACE: 72, PlayerAttribute.DEFENDING: 58,
                       PlayerAttribute.PHYSICAL: 62, PlayerAttribute.PASSING: 86,
                       PlayerAttribute.DRIBBLING: 90, PlayerAttribute.SHOOTING: 72,
                       PlayerAttribute.BALL_CONTROL: 92, PlayerAttribute.AGILITY: 88}},
            {'name': 'Foden', 'number': 47, 'position': Position.LW, 'rating': 88,
             'attrs': {PlayerAttribute.PACE: 85, PlayerAttribute.DEFENDING: 42,
                       PlayerAttribute.PHYSICAL: 58, PlayerAttribute.PASSING: 82,
                       PlayerAttribute.DRIBBLING: 90, PlayerAttribute.SHOOTING: 82,
                       PlayerAttribute.FINISHING: 84, PlayerAttribute.AGILITY: 90,
                       PlayerAttribute.BALL_CONTROL: 90, PlayerAttribute.CURVE: 82}},
            {'name': 'Haaland', 'number': 9, 'position': Position.ST, 'rating': 91,
             'attrs': {PlayerAttribute.PACE: 89, PlayerAttribute.DEFENDING: 35,
                       PlayerAttribute.PHYSICAL: 88, PlayerAttribute.PASSING: 62,
                       PlayerAttribute.DRIBBLING: 78, PlayerAttribute.SHOOTING: 92,
                       PlayerAttribute.FINISHING: 95, PlayerAttribute.POSITIONING: 92,
                       PlayerAttribute.HEADING: 88, PlayerAttribute.SPRINT_SPEED: 90,
                       PlayerAttribute.SHOT_POWER: 92, PlayerAttribute.STRENGTH: 88}},
            {'name': 'Doku', 'number': 11, 'position': Position.RW, 'rating': 82,
             'attrs': {PlayerAttribute.PACE: 94, PlayerAttribute.DEFENDING: 32,
                       PlayerAttribute.PHYSICAL: 62, PlayerAttribute.PASSING: 68,
                       PlayerAttribute.DRIBBLING: 86, PlayerAttribute.SHOOTING: 68,
                       PlayerAttribute.ACCELERATION: 95, PlayerAttribute.AGILITY: 90}},
        ],
        'subs': [
            {'name': 'Ortega', 'number': 18, 'position': Position.GK, 'rating': 82,
             'attrs': {PlayerAttribute.GK_DIVING: 82, PlayerAttribute.GK_HANDLING: 80,
                       PlayerAttribute.GK_REFLEXES: 84, PlayerAttribute.GK_POSITIONING: 80}},
            {'name': 'Akanji', 'number': 25, 'position': Position.CB, 'rating': 83,
             'attrs': {PlayerAttribute.PACE: 72, PlayerAttribute.DEFENDING: 83,
                       PlayerAttribute.PHYSICAL: 80, PlayerAttribute.PASSING: 72}},
            {'name': 'Grealish', 'number': 10, 'position': Position.LW, 'rating': 84,
             'attrs': {PlayerAttribute.PACE: 80, PlayerAttribute.DRIBBLING: 88,
                       PlayerAttribute.PHYSICAL: 68, PlayerAttribute.PASSING: 78,
                       PlayerAttribute.SHOOTING: 72, PlayerAttribute.AGILITY: 86}},
            {'name': 'Alvarez', 'number': 19, 'position': Position.ST, 'rating': 83,
             'attrs': {PlayerAttribute.PACE: 78, PlayerAttribute.DRIBBLING: 82,
                       PlayerAttribute.PHYSICAL: 72, PlayerAttribute.PASSING: 72,
                       PlayerAttribute.SHOOTING: 80, PlayerAttribute.FINISHING: 82}},
        ],
    },

    'bayern_munich': {
        'name': 'FC Bayern Munich',
        'short_name': 'BAY',
        'country': 'Germany',
        'league': 'Bundesliga',
        'rating': 87,
        'home_color': (0.85, 0.1, 0.15),
        'away_color': (1.0, 1.0, 1.0),
        'third_color': (0.1, 0.1, 0.1),
        'gk_color': (0.1, 0.6, 0.1),
        'formation': '4-2-3-1',
        'tactic': 'high_press',
        'mentality': 'attacking',
        'players': [
            {'name': 'Neuer', 'number': 1, 'position': Position.GK, 'rating': 87,
             'attrs': {PlayerAttribute.GK_DIVING: 86, PlayerAttribute.GK_HANDLING: 84,
                       PlayerAttribute.GK_KICKING: 82, PlayerAttribute.GK_REFLEXES: 88,
                       PlayerAttribute.GK_POSITIONING: 88, PlayerAttribute.GK_SPEED: 55}},
            {'name': 'Kimmich', 'number': 6, 'position': Position.RB, 'rating': 87,
             'attrs': {PlayerAttribute.PACE: 70, PlayerAttribute.DEFENDING: 80,
                       PlayerAttribute.PHYSICAL: 72, PlayerAttribute.PASSING: 88,
                       PlayerAttribute.DRIBBLING: 78, PlayerAttribute.SHOOTING: 72,
                       PlayerAttribute.CROSSING: 86, PlayerAttribute.VISION: 84}},
            {'name': 'Upamecano', 'number': 2, 'position': Position.CB, 'rating': 82,
             'attrs': {PlayerAttribute.PACE: 82, PlayerAttribute.DEFENDING: 82,
                       PlayerAttribute.PHYSICAL: 85, PlayerAttribute.PASSING: 58,
                       PlayerAttribute.HEADING: 78, PlayerAttribute.AGGRESSION: 82}},
            {'name': 'Kim', 'number': 3, 'position': Position.CB, 'rating': 83,
             'attrs': {PlayerAttribute.PACE: 68, PlayerAttribute.DEFENDING: 84,
                       PlayerAttribute.PHYSICAL: 82, PlayerAttribute.PASSING: 62,
                       PlayerAttribute.HEADING: 82, PlayerAttribute.STANDING_TACKLE: 84}},
            {'name': 'Davies', 'number': 19, 'position': Position.LB, 'rating': 84,
             'attrs': {PlayerAttribute.PACE: 96, PlayerAttribute.DEFENDING: 72,
                       PlayerAttribute.PHYSICAL: 72, PlayerAttribute.PASSING: 68,
                       PlayerAttribute.DRIBBLING: 82, PlayerAttribute.STAMINA: 90,
                       PlayerAttribute.SPRINT_SPEED: 97, PlayerAttribute.ACCELERATION: 94}},
            {'name': 'Goretzka', 'number': 8, 'position': Position.CDM, 'rating': 84,
             'attrs': {PlayerAttribute.PACE: 72, PlayerAttribute.DEFENDING: 76,
                       PlayerAttribute.PHYSICAL: 84, PlayerAttribute.PASSING: 78,
                       PlayerAttribute.DRIBBLING: 78, PlayerAttribute.SHOOTING: 78,
                       PlayerAttribute.HEADING: 80, PlayerAttribute.STAMINA: 86}},
            {'name': 'Musiala', 'number': 42, 'position': Position.CAM, 'rating': 86,
             'attrs': {PlayerAttribute.PACE: 78, PlayerAttribute.DEFENDING: 38,
                       PlayerAttribute.PHYSICAL: 58, PlayerAttribute.PASSING: 78,
                       PlayerAttribute.DRIBBLING: 92, PlayerAttribute.SHOOTING: 76,
                       PlayerAttribute.BALL_CONTROL: 92, PlayerAttribute.AGILITY: 92,
                       PlayerAttribute.COMPOSURE: 82, PlayerAttribute.BALANCE: 90}},
            {'name': 'Muller', 'number': 25, 'position': Position.CDM, 'rating': 84,
             'attrs': {PlayerAttribute.PACE: 62, PlayerAttribute.DEFENDING: 48,
                       PlayerAttribute.PHYSICAL: 70, PlayerAttribute.PASSING: 82,
                       PlayerAttribute.DRIBBLING: 78, PlayerAttribute.SHOOTING: 80,
                       PlayerAttribute.POSITIONING: 92, PlayerAttribute.VISION: 86,
                       PlayerAttribute.COMPOSURE: 88, PlayerAttribute.REACTIONS: 88}},
            {'name': 'Sane', 'number': 10, 'position': Position.RW, 'rating': 84,
             'attrs': {PlayerAttribute.PACE: 90, PlayerAttribute.DEFENDING: 35,
                       PlayerAttribute.PHYSICAL: 68, PlayerAttribute.PASSING: 72,
                       PlayerAttribute.DRIBBLING: 86, PlayerAttribute.SHOOTING: 80,
                       PlayerAttribute.SPRINT_SPEED: 92, PlayerAttribute.CROSSING: 78}},
            {'name': 'Kane', 'number': 9, 'position': Position.ST, 'rating': 90,
             'attrs': {PlayerAttribute.PACE: 68, PlayerAttribute.DEFENDING: 48,
                       PlayerAttribute.PHYSICAL: 82, PlayerAttribute.PASSING: 85,
                       PlayerAttribute.DRIBBLING: 80, PlayerAttribute.SHOOTING: 92,
                       PlayerAttribute.FINISHING: 94, PlayerAttribute.POSITIONING: 92,
                       PlayerAttribute.HEADING: 82, PlayerAttribute.SHOT_POWER: 88,
                       PlayerAttribute.LONG_SHOTS: 86, PlayerAttribute.PENALTIES: 92}},
            {'name': 'Gnabry', 'number': 7, 'position': Position.LW, 'rating': 82,
             'attrs': {PlayerAttribute.PACE: 86, PlayerAttribute.DEFENDING: 35,
                       PlayerAttribute.PHYSICAL: 65, PlayerAttribute.PASSING: 72,
                       PlayerAttribute.DRIBBLING: 82, PlayerAttribute.SHOOTING: 78,
                       PlayerAttribute.FINISHING: 80, PlayerAttribute.ACCELERATION: 88}},
        ],
        'subs': [
            {'name': 'Ulreich', 'number': 26, 'position': Position.GK, 'rating': 75,
             'attrs': {PlayerAttribute.GK_DIVING: 74, PlayerAttribute.GK_HANDLING: 72,
                       PlayerAttribute.GK_REFLEXES: 76, PlayerAttribute.GK_POSITIONING: 74}},
            {'name': 'de Ligt', 'number': 4, 'position': Position.CB, 'rating': 82,
             'attrs': {PlayerAttribute.PACE: 68, PlayerAttribute.DEFENDING: 82,
                       PlayerAttribute.PHYSICAL: 80, PlayerAttribute.PASSING: 64}},
            {'name': 'Coman', 'number': 11, 'position': Position.RW, 'rating': 82,
             'attrs': {PlayerAttribute.PACE: 92, PlayerAttribute.DRIBBLING: 84,
                       PlayerAttribute.PHYSICAL: 62, PlayerAttribute.PASSING: 70,
                       PlayerAttribute.SHOOTING: 72, PlayerAttribute.CROSSING: 80}},
            {'name': 'Choupo-Moting', 'number': 13, 'position': Position.ST, 'rating': 76,
             'attrs': {PlayerAttribute.PACE: 62, PlayerAttribute.HEADING: 82,
                       PlayerAttribute.PHYSICAL: 82, PlayerAttribute.FINISHING: 76,
                       PlayerAttribute.SHOOTING: 72, PlayerAttribute.STRENGTH: 84}},
        ],
    },

    'liverpool': {
        'name': 'Liverpool FC',
        'short_name': 'LIV',
        'country': 'England',
        'league': 'Premier League',
        'rating': 86,
        'home_color': (0.85, 0.1, 0.1),
        'away_color': (0.1, 0.8, 0.6),
        'third_color': (0.95, 0.85, 0.2),
        'gk_color': (0.1, 0.1, 0.1),
        'formation': '4-3-3',
        'tactic': 'high_press',
        'mentality': 'attacking',
        'players': [
            {'name': 'Alisson', 'number': 1, 'position': Position.GK, 'rating': 89,
             'attrs': {PlayerAttribute.GK_DIVING: 88, PlayerAttribute.GK_HANDLING: 85,
                       PlayerAttribute.GK_KICKING: 85, PlayerAttribute.GK_REFLEXES: 89,
                       PlayerAttribute.GK_POSITIONING: 88, PlayerAttribute.GK_SPEED: 52}},
            {'name': 'Alexander-Arnold', 'number': 66, 'position': Position.RB, 'rating': 86,
             'attrs': {PlayerAttribute.PACE: 76, PlayerAttribute.DEFENDING: 70,
                       PlayerAttribute.PHYSICAL: 68, PlayerAttribute.PASSING: 90,
                       PlayerAttribute.DRIBBLING: 78, PlayerAttribute.SHOOTING: 68,
                       PlayerAttribute.CROSSING: 94, PlayerAttribute.FREE_KICK: 82,
                       PlayerAttribute.VISION: 86, PlayerAttribute.LONG_PASSING: 92}},
            {'name': 'Van Dijk', 'number': 4, 'position': Position.CB, 'rating': 89,
             'attrs': {PlayerAttribute.PACE: 72, PlayerAttribute.DEFENDING: 90,
                       PlayerAttribute.PHYSICAL: 86, PlayerAttribute.PASSING: 72,
                       PlayerAttribute.HEADING: 92, PlayerAttribute.COMPOSURE: 88,
                       PlayerAttribute.STRENGTH: 90, PlayerAttribute.STANDING_TACKLE: 88}},
            {'name': 'Konate', 'number': 5, 'position': Position.CB, 'rating': 83,
             'attrs': {PlayerAttribute.PACE: 82, PlayerAttribute.DEFENDING: 83,
                       PlayerAttribute.PHYSICAL: 84, PlayerAttribute.PASSING: 58,
                       PlayerAttribute.HEADING: 80, PlayerAttribute.STANDING_TACKLE: 82}},
            {'name': 'Robertson', 'number': 26, 'position': Position.LB, 'rating': 84,
             'attrs': {PlayerAttribute.PACE: 82, PlayerAttribute.DEFENDING: 78,
                       PlayerAttribute.PHYSICAL: 72, PlayerAttribute.PASSING: 82,
                       PlayerAttribute.DRIBBLING: 75, PlayerAttribute.CROSSING: 88,
                       PlayerAttribute.STAMINA: 90}},
            {'name': 'Szoboszlai', 'number': 8, 'position': Position.CM, 'rating': 82,
             'attrs': {PlayerAttribute.PACE: 78, PlayerAttribute.DEFENDING: 52,
                       PlayerAttribute.PHYSICAL: 72, PlayerAttribute.PASSING: 80,
                       PlayerAttribute.DRIBBLING: 80, PlayerAttribute.SHOOTING: 78,
                       PlayerAttribute.LONG_SHOTS: 82, PlayerAttribute.STAMINA: 86}},
            {'name': 'Mac Allister', 'number': 10, 'position': Position.CDM, 'rating': 84,
             'attrs': {PlayerAttribute.PACE: 65, PlayerAttribute.DEFENDING: 72,
                       PlayerAttribute.PHYSICAL: 72, PlayerAttribute.PASSING: 84,
                       PlayerAttribute.DRIBBLING: 82, PlayerAttribute.SHOOTING: 72,
                       PlayerAttribute.VISION: 82, PlayerAttribute.COMPOSURE: 84}},
            {'name': 'Gravenberch', 'number': 38, 'position': Position.CM, 'rating': 80,
             'attrs': {PlayerAttribute.PACE: 74, PlayerAttribute.DEFENDING: 68,
                       PlayerAttribute.PHYSICAL: 78, PlayerAttribute.PASSING: 78,
                       PlayerAttribute.DRIBBLING: 80, PlayerAttribute.SHOOTING: 68,
                       PlayerAttribute.STAMINA: 84}},
            {'name': 'Salah', 'number': 11, 'position': Position.RW, 'rating': 88,
             'attrs': {PlayerAttribute.PACE: 90, PlayerAttribute.DEFENDING: 42,
                       PlayerAttribute.PHYSICAL: 72, PlayerAttribute.PASSING: 78,
                       PlayerAttribute.DRIBBLING: 88, PlayerAttribute.SHOOTING: 88,
                       PlayerAttribute.FINISHING: 90, PlayerAttribute.ACCELERATION: 92,
                       PlayerAttribute.AGILITY: 88, PlayerAttribute.COMPOSURE: 86}},
            {'name': 'Nunez', 'number': 9, 'position': Position.ST, 'rating': 83,
             'attrs': {PlayerAttribute.PACE: 90, PlayerAttribute.DEFENDING: 38,
                       PlayerAttribute.PHYSICAL: 78, PlayerAttribute.PASSING: 58,
                       PlayerAttribute.DRIBBLING: 72, PlayerAttribute.SHOOTING: 82,
                       PlayerAttribute.FINISHING: 80, PlayerAttribute.HEADING: 82,
                       PlayerAttribute.SPRINT_SPEED: 92, PlayerAttribute.POSITIONING: 82}},
            {'name': 'Diaz', 'number': 7, 'position': Position.LW, 'rating': 83,
             'attrs': {PlayerAttribute.PACE: 88, PlayerAttribute.DEFENDING: 42,
                       PlayerAttribute.PHYSICAL: 68, PlayerAttribute.PASSING: 72,
                       PlayerAttribute.DRIBBLING: 86, PlayerAttribute.SHOOTING: 72,
                       PlayerAttribute.AGILITY: 90, PlayerAttribute.BALL_CONTROL: 85}},
        ],
        'subs': [
            {'name': 'Kelleher', 'number': 62, 'position': Position.GK, 'rating': 78,
             'attrs': {PlayerAttribute.GK_DIVING: 78, PlayerAttribute.GK_HANDLING: 76,
                       PlayerAttribute.GK_REFLEXES: 80, PlayerAttribute.GK_POSITIONING: 76}},
            {'name': 'Matip', 'number': 32, 'position': Position.CB, 'rating': 80,
             'attrs': {PlayerAttribute.PACE: 62, PlayerAttribute.DEFENDING: 80,
                       PlayerAttribute.PHYSICAL: 78, PlayerAttribute.PASSING: 68}},
            {'name': 'Jota', 'number': 20, 'position': Position.ST, 'rating': 83,
             'attrs': {PlayerAttribute.PACE: 82, PlayerAttribute.DRIBBLING: 82,
                       PlayerAttribute.PHYSICAL: 72, PlayerAttribute.PASSING: 68,
                       PlayerAttribute.SHOOTING: 80, PlayerAttribute.HEADING: 82}},
            {'name': 'Elliott', 'number': 19, 'position': Position.CM, 'rating': 78,
             'attrs': {PlayerAttribute.PACE: 72, PlayerAttribute.DRIBBLING: 80,
                       PlayerAttribute.PHYSICAL: 58, PlayerAttribute.PASSING: 78,
                       PlayerAttribute.SHOOTING: 68, PlayerAttribute.VISION: 78}},
        ],
    },

    'psg': {
        'name': 'Paris Saint-Germain',
        'short_name': 'PSG',
        'country': 'France',
        'league': 'Ligue 1',
        'rating': 87,
        'home_color': (0.0, 0.1, 0.4),
        'away_color': (1.0, 1.0, 1.0),
        'third_color': (0.8, 0.1, 0.2),
        'gk_color': (0.9, 0.6, 0.1),
        'formation': '4-3-3',
        'tactic': 'attacking',
        'mentality': 'attacking',
        'players': [
            {'name': 'Donnarumma', 'number': 99, 'position': Position.GK, 'rating': 87,
             'attrs': {PlayerAttribute.GK_DIVING: 88, PlayerAttribute.GK_HANDLING: 82,
                       PlayerAttribute.GK_KICKING: 72, PlayerAttribute.GK_REFLEXES: 90,
                       PlayerAttribute.GK_POSITIONING: 85, PlayerAttribute.GK_SPEED: 45}},
            {'name': 'Hakimi', 'number': 2, 'position': Position.RB, 'rating': 85,
             'attrs': {PlayerAttribute.PACE: 92, PlayerAttribute.DEFENDING: 72,
                       PlayerAttribute.PHYSICAL: 72, PlayerAttribute.PASSING: 78,
                       PlayerAttribute.DRIBBLING: 82, PlayerAttribute.CROSSING: 84,
                       PlayerAttribute.STAMINA: 88}},
            {'name': 'Marquinhos', 'number': 5, 'position': Position.CB, 'rating': 86,
             'attrs': {PlayerAttribute.PACE: 72, PlayerAttribute.DEFENDING: 86,
                       PlayerAttribute.PHYSICAL: 78, PlayerAttribute.PASSING: 72,
                       PlayerAttribute.HEADING: 82, PlayerAttribute.COMPOSURE: 86,
                       PlayerAttribute.STANDING_TACKLE: 86}},
            {'name': 'Skriniar', 'number': 37, 'position': Position.CB, 'rating': 83,
             'attrs': {PlayerAttribute.PACE: 65, PlayerAttribute.DEFENDING: 85,
                       PlayerAttribute.PHYSICAL: 82, PlayerAttribute.PASSING: 58,
                       PlayerAttribute.HEADING: 82, PlayerAttribute.STANDING_TACKLE: 86}},
            {'name': 'L. Hernandez', 'number': 21, 'position': Position.LB, 'rating': 82,
             'attrs': {PlayerAttribute.PACE: 82, PlayerAttribute.DEFENDING: 80,
                       PlayerAttribute.PHYSICAL: 76, PlayerAttribute.PASSING: 68,
                       PlayerAttribute.DRIBBLING: 72, PlayerAttribute.STAMINA: 84}},
            {'name': 'Vitinha', 'number': 17, 'position': Position.CM, 'rating': 84,
             'attrs': {PlayerAttribute.PACE: 72, PlayerAttribute.DEFENDING: 62,
                       PlayerAttribute.PHYSICAL: 62, PlayerAttribute.PASSING: 84,
                       PlayerAttribute.DRIBBLING: 85, PlayerAttribute.SHOOTING: 72,
                       PlayerAttribute.VISION: 82, PlayerAttribute.BALL_CONTROL: 86}},
            {'name': 'Verratti', 'number': 6, 'position': Position.CDM, 'rating': 86,
             'attrs': {PlayerAttribute.PACE: 62, PlayerAttribute.DEFENDING: 72,
                       PlayerAttribute.PHYSICAL: 58, PlayerAttribute.PASSING: 88,
                       PlayerAttribute.DRIBBLING: 88, PlayerAttribute.SHOOTING: 62,
                       PlayerAttribute.VISION: 86, PlayerAttribute.BALL_CONTROL: 90,
                       PlayerAttribute.AGILITY: 88, PlayerAttribute.COMPOSURE: 86}},
            {'name': 'Zaïre-Emery', 'number': 33, 'position': Position.CM, 'rating': 80,
             'attrs': {PlayerAttribute.PACE: 78, PlayerAttribute.DEFENDING: 65,
                       PlayerAttribute.PHYSICAL: 72, PlayerAttribute.PASSING: 78,
                       PlayerAttribute.DRIBBLING: 78, PlayerAttribute.SHOOTING: 68,
                       PlayerAttribute.STAMINA: 84}},
            {'name': 'Dembele', 'number': 10, 'position': Position.RW, 'rating': 85,
             'attrs': {PlayerAttribute.PACE: 93, PlayerAttribute.DEFENDING: 32,
                       PlayerAttribute.PHYSICAL: 62, PlayerAttribute.PASSING: 78,
                       PlayerAttribute.DRIBBLING: 90, PlayerAttribute.SHOOTING: 72,
                       PlayerAttribute.ACCELERATION: 94, PlayerAttribute.AGILITY: 92,
                       PlayerAttribute.SPRINT_SPEED: 92}},
            {'name': 'Mbappe', 'number': 7, 'position': Position.ST, 'rating': 91,
             'attrs': {PlayerAttribute.PACE: 97, PlayerAttribute.DEFENDING: 36,
                       PlayerAttribute.PHYSICAL: 78, PlayerAttribute.PASSING: 78,
                       PlayerAttribute.DRIBBLING: 90, PlayerAttribute.SHOOTING: 90,
                       PlayerAttribute.FINISHING: 92, PlayerAttribute.POSITIONING: 90,
                       PlayerAttribute.SPRINT_SPEED: 97, PlayerAttribute.ACCELERATION: 96,
                       PlayerAttribute.COMPOSURE: 88, PlayerAttribute.SHOT_POWER: 86}},
            {'name': 'Barcola', 'number': 29, 'position': Position.LW, 'rating': 78,
             'attrs': {PlayerAttribute.PACE: 90, PlayerAttribute.DEFENDING: 28,
                       PlayerAttribute.PHYSICAL: 55, PlayerAttribute.PASSING: 68,
                       PlayerAttribute.DRIBBLING: 82, PlayerAttribute.SHOOTING: 68,
                       PlayerAttribute.ACCELERATION: 92, PlayerAttribute.AGILITY: 88}},
        ],
        'subs': [
            {'name': 'Rico', 'number': 16, 'position': Position.GK, 'rating': 74,
             'attrs': {PlayerAttribute.GK_DIVING: 74, PlayerAttribute.GK_HANDLING: 72,
                       PlayerAttribute.GK_REFLEXES: 76, PlayerAttribute.GK_POSITIONING: 74}},
            {'name': 'Kimpembe', 'number': 3, 'position': Position.CB, 'rating': 78,
             'attrs': {PlayerAttribute.PACE: 76, PlayerAttribute.DEFENDING: 80,
                       PlayerAttribute.PHYSICAL: 80, PlayerAttribute.PASSING: 58}},
            {'name': 'Ugarte', 'number': 4, 'position': Position.CDM, 'rating': 80,
             'attrs': {PlayerAttribute.PACE: 72, PlayerAttribute.DEFENDING: 78,
                       PlayerAttribute.PHYSICAL: 78, PlayerAttribute.PASSING: 72,
                       PlayerAttribute.INTERCEPTIONS: 82, PlayerAttribute.AGGRESSION: 84}},
            {'name': 'Kolo Muani', 'number': 23, 'position': Position.ST, 'rating': 82,
             'attrs': {PlayerAttribute.PACE: 86, PlayerAttribute.DRIBBLING: 78,
                       PlayerAttribute.PHYSICAL: 78, PlayerAttribute.PASSING: 68,
                       PlayerAttribute.SHOOTING: 78, PlayerAttribute.HEADING: 80}},
        ],
    },

    'inter_milan': {
        'name': 'Inter Milan',
        'short_name': 'INT',
        'country': 'Italy',
        'league': 'Serie A',
        'rating': 85,
        'home_color': (0.0, 0.05, 0.5),
        'away_color': (1.0, 1.0, 1.0),
        'third_color': (0.9, 0.8, 0.15),
        'gk_color': (0.1, 0.8, 0.3),
        'formation': '3-5-2',
        'tactic': 'counter_attack',
        'mentality': 'balanced',
        'players': [
            {'name': 'Sommer', 'number': 1, 'position': Position.GK, 'rating': 85,
             'attrs': {PlayerAttribute.GK_DIVING: 84, PlayerAttribute.GK_HANDLING: 82,
                       PlayerAttribute.GK_KICKING: 72, PlayerAttribute.GK_REFLEXES: 86,
                       PlayerAttribute.GK_POSITIONING: 85, PlayerAttribute.GK_SPEED: 42}},
            {'name': 'Pavard', 'number': 28, 'position': Position.CB, 'rating': 82,
             'attrs': {PlayerAttribute.PACE: 72, PlayerAttribute.DEFENDING: 82,
                       PlayerAttribute.PHYSICAL: 78, PlayerAttribute.PASSING: 72,
                       PlayerAttribute.HEADING: 78}},
            {'name': 'Acerbi', 'number': 15, 'position': Position.CB, 'rating': 82,
             'attrs': {PlayerAttribute.PACE: 55, PlayerAttribute.DEFENDING: 84,
                       PlayerAttribute.PHYSICAL: 80, PlayerAttribute.PASSING: 62,
                       PlayerAttribute.HEADING: 82, PlayerAttribute.STANDING_TACKLE: 84}},
            {'name': 'Bastoni', 'number': 95, 'position': Position.CB, 'rating': 84,
             'attrs': {PlayerAttribute.PACE: 68, PlayerAttribute.DEFENDING: 82,
                       PlayerAttribute.PHYSICAL: 76, PlayerAttribute.PASSING: 78,
                       PlayerAttribute.HEADING: 78, PlayerAttribute.LONG_PASSING: 80}},
            {'name': 'Dumfries', 'number': 2, 'position': Position.RWB, 'rating': 81,
             'attrs': {PlayerAttribute.PACE: 86, PlayerAttribute.DEFENDING: 72,
                       PlayerAttribute.PHYSICAL: 82, PlayerAttribute.PASSING: 68,
                       PlayerAttribute.CROSSING: 78, PlayerAttribute.STAMINA: 88}},
            {'name': 'Barella', 'number': 23, 'position': Position.CM, 'rating': 86,
             'attrs': {PlayerAttribute.PACE: 78, PlayerAttribute.DEFENDING: 72,
                       PlayerAttribute.PHYSICAL: 78, PlayerAttribute.PASSING: 84,
                       PlayerAttribute.DRIBBLING: 82, PlayerAttribute.SHOOTING: 78,
                       PlayerAttribute.VISION: 82, PlayerAttribute.STAMINA: 90,
                       PlayerAttribute.LONG_SHOTS: 80}},
            {'name': 'Calhanoglu', 'number': 20, 'position': Position.CDM, 'rating': 84,
             'attrs': {PlayerAttribute.PACE: 58, PlayerAttribute.DEFENDING: 68,
                       PlayerAttribute.PHYSICAL: 72, PlayerAttribute.PASSING: 84,
                       PlayerAttribute.DRIBBLING: 78, PlayerAttribute.SHOOTING: 80,
                       PlayerAttribute.FREE_KICK: 88, PlayerAttribute.LONG_SHOTS: 86}},
            {'name': 'Mkhitaryan', 'number': 22, 'position': Position.CM, 'rating': 81,
             'attrs': {PlayerAttribute.PACE: 68, PlayerAttribute.DEFENDING: 55,
                       PlayerAttribute.PHYSICAL: 68, PlayerAttribute.PASSING: 82,
                       PlayerAttribute.DRIBBLING: 82, PlayerAttribute.SHOOTING: 76,
                       PlayerAttribute.VISION: 82}},
            {'name': 'Dimarco', 'number': 32, 'position': Position.LWB, 'rating': 83,
             'attrs': {PlayerAttribute.PACE: 78, PlayerAttribute.DEFENDING: 68,
                       PlayerAttribute.PHYSICAL: 68, PlayerAttribute.PASSING: 82,
                       PlayerAttribute.CROSSING: 90, PlayerAttribute.FREE_KICK: 82,
                       PlayerAttribute.STAMINA: 86}},
            {'name': 'Lautaro', 'number': 10, 'position': Position.ST, 'rating': 87,
             'attrs': {PlayerAttribute.PACE: 82, PlayerAttribute.DEFENDING: 42,
                       PlayerAttribute.PHYSICAL: 78, PlayerAttribute.PASSING: 68,
                       PlayerAttribute.DRIBBLING: 82, PlayerAttribute.SHOOTING: 86,
                       PlayerAttribute.FINISHING: 88, PlayerAttribute.POSITIONING: 88,
                       PlayerAttribute.COMPOSURE: 84}},
            {'name': 'Thuram', 'number': 9, 'position': Position.ST, 'rating': 83,
             'attrs': {PlayerAttribute.PACE: 86, PlayerAttribute.DEFENDING: 38,
                       PlayerAttribute.PHYSICAL: 82, PlayerAttribute.PASSING: 62,
                       PlayerAttribute.DRIBBLING: 78, PlayerAttribute.SHOOTING: 78,
                       PlayerAttribute.HEADING: 78, PlayerAttribute.STRENGTH: 82}},
        ],
        'subs': [
            {'name': 'Di Gennaro', 'number': 21, 'position': Position.GK, 'rating': 68,
             'attrs': {PlayerAttribute.GK_DIVING: 68, PlayerAttribute.GK_HANDLING: 66,
                       PlayerAttribute.GK_REFLEXES: 70, PlayerAttribute.GK_POSITIONING: 68}},
            {'name': 'Darmian', 'number': 36, 'position': Position.CB, 'rating': 78,
             'attrs': {PlayerAttribute.PACE: 65, PlayerAttribute.DEFENDING: 78,
                       PlayerAttribute.PHYSICAL: 72, PlayerAttribute.PASSING: 68}},
            {'name': 'Frattesi', 'number': 16, 'position': Position.CM, 'rating': 79,
             'attrs': {PlayerAttribute.PACE: 76, PlayerAttribute.DEFENDING: 62,
                       PlayerAttribute.PHYSICAL: 76, PlayerAttribute.PASSING: 72,
                       PlayerAttribute.SHOOTING: 76, PlayerAttribute.STAMINA: 84}},
            {'name': 'Arnautovic', 'number': 8, 'position': Position.ST, 'rating': 76,
             'attrs': {PlayerAttribute.PACE: 62, PlayerAttribute.HEADING: 80,
                       PlayerAttribute.PHYSICAL: 82, PlayerAttribute.FINISHING: 76,
                       PlayerAttribute.SHOOTING: 74, PlayerAttribute.STRENGTH: 84}},
        ],
    },

    'borussia_dortmund': {
        'name': 'Borussia Dortmund',
        'short_name': 'BVB',
        'country': 'Germany',
        'league': 'Bundesliga',
        'rating': 83,
        'home_color': (1.0, 0.85, 0.0),
        'away_color': (0.0, 0.0, 0.0),
        'third_color': (0.3, 0.3, 0.3),
        'gk_color': (0.8, 0.2, 0.1),
        'formation': '4-2-3-1',
        'tactic': 'counter_attack',
        'mentality': 'balanced',
        'players': [
            {'name': 'Kobel', 'number': 1, 'position': Position.GK, 'rating': 84,
             'attrs': {PlayerAttribute.GK_DIVING: 84, PlayerAttribute.GK_HANDLING: 80,
                       PlayerAttribute.GK_KICKING: 72, PlayerAttribute.GK_REFLEXES: 85,
                       PlayerAttribute.GK_POSITIONING: 82, PlayerAttribute.GK_SPEED: 45}},
            {'name': 'Ryerson', 'number': 26, 'position': Position.RB, 'rating': 78,
             'attrs': {PlayerAttribute.PACE: 82, PlayerAttribute.DEFENDING: 74,
                       PlayerAttribute.PHYSICAL: 72, PlayerAttribute.PASSING: 68,
                       PlayerAttribute.DRIBBLING: 72, PlayerAttribute.STAMINA: 84}},
            {'name': 'Hummels', 'number': 15, 'position': Position.CB, 'rating': 82,
             'attrs': {PlayerAttribute.PACE: 42, PlayerAttribute.DEFENDING: 86,
                       PlayerAttribute.PHYSICAL: 76, PlayerAttribute.PASSING: 78,
                       PlayerAttribute.HEADING: 85, PlayerAttribute.COMPOSURE: 88,
                       PlayerAttribute.VISION: 78, PlayerAttribute.LONG_PASSING: 82}},
            {'name': 'Schlotterbeck', 'number': 4, 'position': Position.CB, 'rating': 81,
             'attrs': {PlayerAttribute.PACE: 72, PlayerAttribute.DEFENDING: 82,
                       PlayerAttribute.PHYSICAL: 80, PlayerAttribute.PASSING: 68,
                       PlayerAttribute.HEADING: 78, PlayerAttribute.AGGRESSION: 78}},
            {'name': 'Maatsen', 'number': 22, 'position': Position.LB, 'rating': 78,
             'attrs': {PlayerAttribute.PACE: 86, PlayerAttribute.DEFENDING: 72,
                       PlayerAttribute.PHYSICAL: 65, PlayerAttribute.PASSING: 72,
                       PlayerAttribute.DRIBBLING: 76, PlayerAttribute.STAMINA: 86}},
            {'name': 'Can', 'number': 23, 'position': Position.CDM, 'rating': 78,
             'attrs': {PlayerAttribute.PACE: 62, PlayerAttribute.DEFENDING: 76,
                       PlayerAttribute.PHYSICAL: 82, PlayerAttribute.PASSING: 72,
                       PlayerAttribute.SHOOTING: 72, PlayerAttribute.HEADING: 78}},
            {'name': 'Sabitzer', 'number': 20, 'position': Position.CDM, 'rating': 80,
             'attrs': {PlayerAttribute.PACE: 72, PlayerAttribute.DEFENDING: 70,
                       PlayerAttribute.PHYSICAL: 76, PlayerAttribute.PASSING: 78,
                       PlayerAttribute.DRIBBLING: 76, PlayerAttribute.SHOOTING: 78,
                       PlayerAttribute.STAMINA: 88}},
            {'name': 'Sancho', 'number': 10, 'position': Position.LW, 'rating': 80,
             'attrs': {PlayerAttribute.PACE: 82, PlayerAttribute.DEFENDING: 32,
                       PlayerAttribute.PHYSICAL: 58, PlayerAttribute.PASSING: 78,
                       PlayerAttribute.DRIBBLING: 88, PlayerAttribute.SHOOTING: 72,
                       PlayerAttribute.AGILITY: 90, PlayerAttribute.BALL_CONTROL: 88}},
            {'name': 'Brandt', 'number': 19, 'position': Position.CAM, 'rating': 82,
             'attrs': {PlayerAttribute.PACE: 72, PlayerAttribute.DEFENDING: 42,
                       PlayerAttribute.PHYSICAL: 62, PlayerAttribute.PASSING: 82,
                       PlayerAttribute.DRIBBLING: 82, PlayerAttribute.SHOOTING: 78,
                       PlayerAttribute.VISION: 84, PlayerAttribute.FREE_KICK: 78}},
            {'name': 'Adeyemi', 'number': 27, 'position': Position.RW, 'rating': 80,
             'attrs': {PlayerAttribute.PACE: 94, PlayerAttribute.DEFENDING: 28,
                       PlayerAttribute.PHYSICAL: 58, PlayerAttribute.PASSING: 65,
                       PlayerAttribute.DRIBBLING: 82, PlayerAttribute.SHOOTING: 72,
                       PlayerAttribute.SPRINT_SPEED: 95, PlayerAttribute.ACCELERATION: 93}},
            {'name': 'Fullkrug', 'number': 9, 'position': Position.ST, 'rating': 82,
             'attrs': {PlayerAttribute.PACE: 62, PlayerAttribute.DEFENDING: 38,
                       PlayerAttribute.PHYSICAL: 82, PlayerAttribute.PASSING: 62,
                       PlayerAttribute.DRIBBLING: 68, PlayerAttribute.SHOOTING: 82,
                       PlayerAttribute.FINISHING: 84, PlayerAttribute.HEADING: 88,
                       PlayerAttribute.STRENGTH: 84, PlayerAttribute.POSITIONING: 84}},
        ],
        'subs': [
            {'name': 'Meyer', 'number': 35, 'position': Position.GK, 'rating': 72,
             'attrs': {PlayerAttribute.GK_DIVING: 72, PlayerAttribute.GK_HANDLING: 70,
                       PlayerAttribute.GK_REFLEXES: 74, PlayerAttribute.GK_POSITIONING: 72}},
            {'name': 'Sule', 'number': 25, 'position': Position.CB, 'rating': 78,
             'attrs': {PlayerAttribute.PACE: 72, PlayerAttribute.DEFENDING: 80,
                       PlayerAttribute.PHYSICAL: 84, PlayerAttribute.PASSING: 62}},
            {'name': 'Reus', 'number': 11, 'position': Position.CAM, 'rating': 80,
             'attrs': {PlayerAttribute.PACE: 72, PlayerAttribute.DRIBBLING: 84,
                       PlayerAttribute.PHYSICAL: 58, PlayerAttribute.PASSING: 82,
                       PlayerAttribute.SHOOTING: 82, PlayerAttribute.VISION: 84}},
            {'name': 'Malen', 'number': 21, 'position': Position.ST, 'rating': 80,
             'attrs': {PlayerAttribute.PACE: 90, PlayerAttribute.DRIBBLING: 82,
                       PlayerAttribute.PHYSICAL: 62, PlayerAttribute.PASSING: 68,
                       PlayerAttribute.SHOOTING: 78, PlayerAttribute.FINISHING: 80}},
        ],
    },
}

# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

def get_team(team_id: str) -> dict:
    return TEAMS.get(team_id, None)

def get_team_list() -> list:
    return [(tid, t['name'], t['rating']) for tid, t in TEAMS.items()]

def get_teams_by_league(league: str) -> list:
    return [(tid, t) for tid, t in TEAMS.items() if t['league'] == league]

def get_all_leagues() -> list:
    leagues = set()
    for t in TEAMS.values():
        leagues.add(t['league'])
    return sorted(list(leagues))

def get_player_overall(player_data: dict) -> int:
    return player_data.get('rating', 70)

def get_player_attribute(player_data: dict, attr: PlayerAttribute, default: int = 50) -> int:
    return player_data.get('attrs', {}).get(attr, default)

def get_team_overall(team_id: str) -> int:
    team = get_team(team_id)
    if not team:
        return 70
    ratings = [p['rating'] for p in team['players']]
    return int(sum(ratings) / len(ratings)) if ratings else 70

def get_starting_eleven(team_id: str) -> list:
    team = get_team(team_id)
    if not team:
        return []
    return team['players'][:11]

def get_substitutes(team_id: str) -> list:
    team = get_team(team_id)
    if not team:
        return []
    return team.get('subs', [])
